"""Generates migration script template."""
from alembic import op
import sqlalchemy as sa


def process_revision_directives(context, revision, directives):
    """Hook to customise autogenerated migration scripts."""
    pass
