"""
Shared state definitions for LangGraph workflows.
"""

from typing import TypedDict, List, Dict, Any, Optional
import operator
from typing_extensions import Annotated

from app.services.document_processor import DocumentChunk
from app.services.extraction_service import Entity, Relationship


def _last_value(existing, new):
    """Reducer that always keeps the latest value (last-writer-wins)."""
    return new


class ResearchState(TypedDict):
    """
    The shared state passed between agents in the LangGraph workflows.
    
    Fields that may be written by parallel nodes use the _last_value reducer
    to prevent INVALID_CONCURRENT_GRAPH_UPDATE errors.
    """
    
    # ── Core Inputs / Outputs ──
    query: Optional[str]                     # The user's query or question
    document_id: Optional[str]               # ID of the document being processed or queried
    file_path: Optional[str]                 # Local path to the uploaded file
    file_type: Optional[str]                 # 'pdf' or 'docx'
    
    # ── Graph Mode ──
    # "cooccurrence" = InfraNodus-style co-occurrence graph (fast, no LLM)
    # "llm"          = LLM-based entity/relationship extraction (rich, slower)
    # "both"         = Run both modes and merge results
    graph_mode: Optional[str]
    
    # ── Workflow Control ──
    current_step: Annotated[str, _last_value]   # Name of the current active step
    errors: Annotated[List[str], operator.add]   # List of errors encountered (additive)
    
    # ── Document Processing State ──
    chunks: List[DocumentChunk]              # Text chunks extracted from the document
    chunk_texts: List[str]                   # Just the string content of the chunks
    
    # ── Extraction State (LLM mode) ──
    entities: List[Entity]                   # Extracted entities
    relationships: List[Relationship]        # Extracted relationships
    
    # ── Co-occurrence State (InfraNodus mode) ──
    cooccurrence_nodes: List[Dict[str, Any]]   # [{name, frequency}]
    cooccurrence_edges: List[Dict[str, Any]]   # [{source, target, weight}]
    
    # ── Retrieval & RAG State ──
    vector_context: List[Dict[str, Any]]     # Context retrieved from ChromaDB
    graph_context: List[Dict[str, Any]]      # Context retrieved from Neo4j
    merged_context: str                      # Formatted context ready for the LLM
    answer: str                              # The final answer generated by Hybrid RAG
    
    # ── Research & Insights State ──
    subtopics: List[str]                     # Subtopics generated by the planner
    insights: List[str]                      # Insights generated by the Insight Agent
    report: str                              # Final structured report

